version: '3.8'

services:
  ${SERVICE_NAME}:
    image: ${IMAGE_NAME}:latest

    deploy:
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.http.routers.${SERVICE_NAME}.rule=Host(`${DOMAIN_NAME}`)
        - traefik.http.routers.${SERVICE_NAME}.entrypoints=websecure
        - traefik.http.routers.${SERVICE_NAME}.tls.certresolver=letsencryptresolver
        - traefik.http.services.${SERVICE_NAME}.loadbalancer.server.port=${INTERNAL_PORT}

    networks:
      - IcodeNet

networks:
  IcodeNet:
    external: true
